### ISSUE TITLE
some objects returned null while parsing

### ISSUE THREAD

**Issue by reydus** [thibauts/parse-3ds#4]
I am using a .3ds file representing a simple component cube I made in Sketchup. The program returns:

```
  return tree.children.filter(function(chunk) {
              ^

TypeError: Cannot read property 'children' of null
    at getChildrenChunks (C:\Users\raymondm\node_modules\parse-3ds\index.js:214:15)
    at getChildChunk (C:\Users\raymondm\node_modules\parse-3ds\index.js:206:16)
    at C:\Users\raymondm\node_modules\parse-3ds\index.js:275:29
    at Array.map (<anonymous>)
    at module.exports (C:\Users\raymondm\node_modules\parse-3ds\index.js:272:35)
    at Object.<anonymous> (C:\Users\raymondm\Documents\parse-3ds-master\launch.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```

that is because

```
      var triMeshChunk = getChildChunk(objectChunk, 0x4100);
```

returned null and then passed to

```
      var vertexListChunk = getChildChunk(triMeshChunk, 0x4110);
```
Here's the .3ds file (change extension so I could attach it here, also available in my [fork](https://github.com/reydus/parse-3ds)
[cubic.txt](https://github.com/thibauts/parse-3ds/files/4260973/cubic.txt)

**Comment by reydus** [comment]
Okay, so, after some experimentation, I came to the conclusion that the .3ds file I am working with had a ```camera``` object, which the algorithm tried getting a mesh out of, yielding a ```null``` object whose properties don't exist.

I am working in my fork to better adapt this only include objects that have a mesh in the [fork](https://github.com/reydus/parse-3ds).
